# Generated by Django 3.2.2 on 2021-06-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hc',
            name='like',
            field=models.CharField(choices=[('sport', 'Sport'), ('movie', 'Movie'), ('animal', 'Animal'), ('music', 'Music')], max_length=80, null=True),
        ),
    ]
