# Generated by Django 3.2.2 on 2021-06-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc', '0002_hc_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='hc',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='hc',
            name='like',
            field=models.CharField(choices=[('music', 'Music'), ('movie', 'Movie'), ('sport', 'Sport'), ('animal', 'Animal')], max_length=80, null=True),
        ),
    ]
