# Generated by Django 3.2.2 on 2021-06-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc', '0003_auto_20210629_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hc',
            name='image',
        ),
        migrations.AddField(
            model_name='hc',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='hc',
            name='like',
            field=models.CharField(choices=[('movie', 'Movie'), ('sport', 'Sport'), ('music', 'Music'), ('animal', 'Animal')], max_length=80, null=True),
        ),
    ]
