# Generated by Django 3.2.2 on 2021-06-29 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hc', '0004_auto_20210629_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hc',
            name='photo',
        ),
        migrations.AlterField(
            model_name='hc',
            name='like',
            field=models.CharField(choices=[('sport', 'Sport'), ('animal', 'Animal'), ('music', 'Music'), ('movie', 'Movie')], max_length=80, null=True),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('hc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hc.hc')),
            ],
        ),
    ]
