# Generated by Django 3.2.4 on 2021-06-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc', '0005_auto_20210629_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hc',
            name='like',
            field=models.CharField(choices=[('animal', 'Animal'), ('music', 'Music'), ('sport', 'Sport'), ('movie', 'Movie')], max_length=80, null=True),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
