# Generated by Django 3.2.4 on 2021-06-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc', '0006_auto_20210629_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='hc',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Hc/'),
        ),
        migrations.AlterField(
            model_name='hc',
            name='like',
            field=models.CharField(choices=[('sport', 'Sport'), ('movie', 'Movie'), ('animal', 'Animal'), ('music', 'Music')], max_length=80, null=True),
        ),
    ]
